# Generated by Django 2.2.6 on 2019-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='s_grade',
        ),
        migrations.AlterField(
            model_name='student',
            name='s_major',
            field=models.CharField(max_length=1000),
        ),
    ]
