# Generated by Django 2.2.6 on 2019-11-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191122_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_major',
        ),
    ]
